[package]
name = "ynufe_libs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0"
serde_json = "1.0"
anyhow  = "1.0"
thiserror = "2.0"
reqwest = {version = "0.12",features = ["json"]}
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
